apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: myhospital
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  EUREKA_INSTANCE_HOSTNAME: "eureka-server"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: myhospital
data:
  # Patient DB
  PATIENT_DB_HOST: "patient-mysql"
  PATIENT_DB_PORT: "3306"
  PATIENT_DB_NAME: "patientdb"
  # Doctor DB
  DOCTOR_DB_HOST: "doctor-mysql"
  DOCTOR_DB_PORT: "3306"
  DOCTOR_DB_NAME: "doctordb"
  # Appointment DB
  APPOINTMENT_DB_HOST: "appointment-mysql"
  APPOINTMENT_DB_PORT: "3306"
  APPOINTMENT_DB_NAME: "appointmentdb"
