apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # "root" en base64
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
